# This is a basic workflow to help you get started with Actions

name: Build

concurrency:
  group: ${{ github.workflow }}@tag
  cancel-in-progress: true
# Controls when the workflow will run

on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          export GH_TAG=${GITHUB_REF##*/}
          cp README.md bookmark
          zip -r bookmark.zip bookmark/*
          # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
          cat>_data.yaml<<EOF
          tag_name: ${GH_TAG}
          make_latest: legacy
          
          
          EOF
          data=`yq -P -o json -I=0 _data.yaml`
          curl -L -s -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases \
              -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
